version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 8090:9090
    volumes:
      - ~/prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command: --path.rootfs=/host
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 8300:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
