version: '3'

services:
  conduit:
    image: matrixconduit/matrix-conduit:latest
    container_name: matrix-conduit
    restart: unless-stopped
    ports:
      - 8167:6167
    volumes:
      - matrix_rocksdb:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: ${MATRIX_SERVER_HOST}
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org","aria-net.org","mozilla.org","tchncs.de","tedomum.net","utwente.io"]'
      CONDUIT_MAX_CONCURRENT_REQUESTS: 100
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: '' # Ignore this

  db:
    image: postgres:16-alpine
    container_name: matrix-db
    restart: unless-stopped
    volumes:
      - matrix_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=matrix
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]

  mautrix-discord:
    image: dock.mau.dev/mautrix/discord:latest
    container_name: mautrix-discord
    restart: unless-stopped
    volumes:
      - ${MAUTRIX-DISCORD_DIR}:/data
    depends_on:
      db:
        condition: service_healthy

  mautrix-slack:
    image: dock.mau.dev/mautrix/slack:latest
    container_name: mautrix-slack
    restart: unless-stopped
    volumes:
      - ${MAUTRIX-SLACK_DIR}:/data
    depends_on:
      db:
        condition: service_healthy

  heisenbridge:
    image: hif1/heisenbridge:latest
    container_name: matrix-heisenbridge
    restart: unless-stopped
    command: -c /data/registration.yaml -p 9898 http://matrix-conduit:6167
    volumes:
      - ${HEISENBRIDGE_DIR}:/data
    depends_on:
      conduit:
        condition: service_started

  cinny:
    image: ajbura/cinny:latest
    container_name: matrix-cinny
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${CINNY_CONFIG}:/app/config.json
    depends_on:
      conduit:
        condition: service_started

volumes:
  matrix_rocksdb:
    name: matrix_rocksdb
  matrix_db:
    name: matrix_db

networks:
  matrix:
    name: matrix
