version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-server
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS="127.0.0.1, ${NEXTCLOUD_HOST}"
      - OVERWRITEPROTOCOL=https
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - nextcloud_radis:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]

volumes:
  nextcloud_data:
    name: nextcloud_data
  nextcloud_db:
    name: nextcloud_db
  nextcloud_radis:
    name: nextcloud_radis

networks:
  nextcloud:
    name: nextcloud
