version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8800:8000
    volumes:
      - woodpecker-server_data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_HOST=https://${WOODPECKER_HOST}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://${YOUR_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${YOUR_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${YOUR_GITEA_CLIENT_SECRET}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - woodpecker-agent_config:/etc/woodpecker:ro
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    depends_on:
      woodpecker-server:
        condition: service_started

volumes:
  woodpecker-server_data:
    name: woodpecker-server_data
  woodpecker-agent_config:
    name: woodpecker-agent_data

networks:
  woodpecker:
    name: woodpecker
